development:
  adapter: postgresql
  encoding: unicode
  database: dns_dev
  pool: 5
  username: postgres
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: dns_test
  pool: 5
  username: postgres
  password:
